name: mju_food_trace_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_google_location_picker: ^0.0.3
  flutter_typeahead: ^4.6.2
  path_provider: ^2.1.0
  geolocator:
  geocoding:
  file_picker: ^5.2.7
  flutter_datetime_picker: ^1.5.1
  intl: ^0.18.0
  provider: ^6.0.5
  http: ^0.13.5
  quickalert:
  flutter_session_manager: ^1.0.2
  google_maps_flutter: ^2.3.0
  image_gallery_saver: ^2.0.3
  dio: ^5.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - images/logo.png
    - images/farmer_icon.png
    - images/factory_icon.png
    - images/check_correct.gif
    - images/check_correct2.gif
    - images/admin_icon.png
    - images/ftmju_header_logo.png
    - images/assembly-line.gif

  fonts:
    - family: Itim
      fonts:
        - asset: fonts/Itim-Regular.otf
